### PR TITLE
Use react-cdk #26

### LINKED ISSUE #26: Use react-cdk
We need to use React CDK for this project.
So, we can have some common base where we use everywhere.

### PR DESCRIPTION
**Pull request by kasunben**
Fix #26

### CODE REVIEW

**Comment by arunoda** [comment]
@thinkholic could you fix the conflict.

**Comment by kasunben** [comment]
Doing it.

**Comment by kasunben** [comment]
@arunoda Fixed.

**Comment by arunoda** [comment]
Have you run `npm run lintfix`?

**Comment by arunoda** [comment]
@thinkholic seems like we need to fix some conflicts again.

**Comment by kasunben** [comment]
@arunoda Fixed merge conflicts

**Comment by arunoda** [comment]
Great.

**Pull request merged**
