### PR TITLE
Write test cases for dataStore

### LINKED ISSUE #36: Write tests
We need to write tests for the [dataStore](https://github.com/kadirahq/storybook-addon-comments/blob/master/src/manager/containers/CommentsPanel/dataStore.js) and the [container](https://github.com/kadirahq/storybook-addon-comments/blob/master/src/manager/containers/CommentsPanel/index.js).

### PR DESCRIPTION
**Pull request by kasunben**
Fixes #36

### CODE REVIEW

**Comment by arunoda** [comment]
**[Storybook Hub](https://hub.getstorybook.io/)** is building storybook for every commit in this PR.

**Latest Storybook: https://f79c8622-05f5-4bbd-80bb-5eb6d50ce253.sbook.io/**
<sub>( Visit [here]($INFOURL) for more info )</sub>

> _This comment is automatically added by Storybook Hub_

**Comment by arunoda** [comment]
@thinkholic Are we going to write more test cases?

**Comment by kasunben** [comment]
@arunoda Done for dataStore.

**Comment by arunoda** [comment]
@thinkholic great.
I've added few more stuff for the dataStore, could you test them too?

**Comment by kasunben** [comment]
@arunoda Updated

**Pull request merged**
