### PR TITLE
Multiline comments support #5

### PR DESCRIPTION
**Pull request by kasunben**
Fix for #5

### CODE REVIEW

**Review by arunoda — CHANGES_REQUESTED** [review]
This is great. I made some few style changes.
We need make this textarea auto expandable.
But we need to expand it only few lines. Otherwise design will looks off.

For an example, see how Slack is doing it.
We need to mimic that.

**Comment by kasunben** [comment]
added auto-expandable support, but also set max-height to limit the expandable height.

**Comment by kasunben** [comment]
@arunoda Button resize now okay.

**Comment by kasunben** [comment]
Updated.

**Review by arunoda — APPROVED** [review]

**Pull request merged**
